// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dtQ34XSrD6wkMINaj2MNKcHunDwte2w',
    appId: '1:1008198679551:web:b23ef16c402341e16b45ca',
    messagingSenderId: '1008198679551',
    projectId: 'story-da733',
    authDomain: 'story-da733.firebaseapp.com',
    databaseURL: 'https://story-da733.firebaseio.com',
    storageBucket: 'story-da733.appspot.com',
    measurementId: 'G-FXHHWF07YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jysf8AepW8zvPJDSFbpYW2XjgPo0X8M',
    appId: '1:1008198679551:android:6cc610c5bc54be656b45ca',
    messagingSenderId: '1008198679551',
    projectId: 'story-da733',
    databaseURL: 'https://story-da733.firebaseio.com',
    storageBucket: 'story-da733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61x2s9ZnWTFdZckOehgnBjmylZkrgmk8',
    appId: '1:1008198679551:ios:34be96ae53f3ba3e6b45ca',
    messagingSenderId: '1008198679551',
    projectId: 'story-da733',
    databaseURL: 'https://story-da733.firebaseio.com',
    storageBucket: 'story-da733.appspot.com',
    iosClientId: '1008198679551-k16s1evsopcv84kki4pdt1esco7glgqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.glorycity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA61x2s9ZnWTFdZckOehgnBjmylZkrgmk8',
    appId: '1:1008198679551:ios:34be96ae53f3ba3e6b45ca',
    messagingSenderId: '1008198679551',
    projectId: 'story-da733',
    databaseURL: 'https://story-da733.firebaseio.com',
    storageBucket: 'story-da733.appspot.com',
    iosClientId: '1008198679551-k16s1evsopcv84kki4pdt1esco7glgqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.glorycity',
  );
}
